### ISSUE TITLE
Add Wormhole Generator: Argus to Minimap Reloacation List

### ISSUE THREAD

**Issue by deikun** [Repooc/ElvUI_SLE#43]
Requesting to add the new engineering Wormhole Generator: Argus toy to the relocation list.

**Comment by Repooc** [comment]
please submit all issue and requests to https://git.tukui.org/Darth_Predator/elvui-shadowandlight as this was just a place holder for something I was going to try with automating cureforge uploads but just forgot to delete the repo from github
